### PR TITLE
add -E option to filepath command

### PR DESCRIPTION
**Pull request by stm85**
-E	
Specifies the <exit-code> if HDBSQL returns an error. Values are: OKAY = 0, ERROR = 1, USAGE = 2, SQLERROR = 3, and VAR = 4.

if -E is not set when using-I option the sql will not fail on first error and still continue running the sql commands inside the file. If the last command is successfully, the whole run is market as successfully

### CODE REVIEW

**Comment by rainerleber** [comment]
Hi @stm85 thanks for the PR. Sorry for the delay i will take a look and test it by my self after that i will merge the pr as fast as possible.

**Comment by rainerleber** [comment]
@stm85 Could you please add a changelog fragment

**Comment by stm85** [comment]
sure :-D

**Comment by rainerleber** [comment]
@stm85 i edit a typo

**Review by rainerleber — APPROVED** [review]
lgtm

**Pull request merged**
